import { config } from 'dotenv';
import { resolve } from 'path';
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, Timestamp } from 'firebase/firestore';

// Load environment variables
config({ path: resolve(__dirname, '../.env.local') });

// Firebase configuration
const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const sampleJobs = [
  {
    agencyId: 'sample-agency-001',
    title: 'Senior Full Stack Developer',
    description: 'We are looking for an experienced Full Stack Developer to join our dynamic team. You will be responsible for developing and maintaining web applications using modern technologies. The ideal candidate has strong experience with React, Node.js, and cloud platforms.',
    tagline: 'Build scalable web applications with cutting-edge tech',
    companyName: 'TechCorp Solutions',
    location: 'Manila',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'full-time' as const,
    salaryMin: 80000,
    salaryMax: 120000,
    currency: 'PHP',
    experienceRequired: 5,
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
    category: 'IT & Software Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Digital Marketing Manager',
    description: 'Join our marketing team to lead digital campaigns across multiple channels. You will develop strategies, manage budgets, and analyze performance metrics to drive business growth.',
    tagline: 'Drive growth through innovative digital strategies',
    companyName: 'Marketing Pro Inc',
    location: 'Cebu',
    country: 'Philippines',
    locationType: 'on-site' as const,
    jobType: 'full-time' as const,
    salaryMin: 50000,
    salaryMax: 75000,
    currency: 'PHP',
    experienceRequired: 3,
    skills: ['SEO', 'Google Ads', 'Social Media', 'Analytics', 'Content Strategy'],
    category: 'Marketing & Communications',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'UX/UI Designer',
    description: 'Create beautiful and intuitive user experiences for our mobile and web applications. Work closely with product and engineering teams to bring designs to life.',
    tagline: 'Design user experiences that delight',
    companyName: 'Creative Studio PH',
    location: 'Makati',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'full-time' as const,
    salaryMin: 60000,
    salaryMax: 90000,
    currency: 'PHP',
    experienceRequired: 3,
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'Design Systems'],
    category: 'Design & Creative',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Data Scientist',
    description: 'Analyze complex datasets and build predictive models to drive business decisions. Work with stakeholders to identify opportunities and implement data-driven solutions.',
    tagline: 'Turn data into actionable insights',
    companyName: 'DataTech Analytics',
    location: 'Bonifacio Global City',
    country: 'Philippines',
    locationType: 'remote' as const,
    jobType: 'full-time' as const,
    salaryMin: 90000,
    salaryMax: 140000,
    currency: 'PHP',
    experienceRequired: 4,
    skills: ['Python', 'Machine Learning', 'SQL', 'TensorFlow', 'Data Visualization'],
    category: 'Data Science & Analytics',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Mobile App Developer (iOS)',
    description: 'Develop and maintain iOS applications for our growing user base. Collaborate with designers and backend developers to create seamless mobile experiences.',
    tagline: 'Build amazing iOS apps for millions of users',
    companyName: 'AppVentures PH',
    location: 'Quezon City',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'full-time' as const,
    salaryMin: 70000,
    salaryMax: 110000,
    currency: 'PHP',
    experienceRequired: 3,
    skills: ['Swift', 'SwiftUI', 'iOS SDK', 'REST APIs', 'Git'],
    category: 'IT & Software Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Customer Success Manager',
    description: 'Build and maintain strong relationships with our enterprise clients. Ensure customer satisfaction and drive product adoption through excellent service.',
    tagline: 'Help customers succeed and grow',
    companyName: 'SaaS Solutions Ltd',
    location: 'Manila',
    country: 'Philippines',
    locationType: 'on-site' as const,
    jobType: 'full-time' as const,
    salaryMin: 45000,
    salaryMax: 65000,
    currency: 'PHP',
    experienceRequired: 2,
    skills: ['Customer Relations', 'Communication', 'CRM', 'Problem Solving', 'SaaS'],
    category: 'Customer Service & Support',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'DevOps Engineer',
    description: 'Maintain and improve our cloud infrastructure. Implement CI/CD pipelines and ensure high availability of our systems.',
    tagline: 'Build reliable infrastructure at scale',
    companyName: 'CloudNine Systems',
    location: 'Pasig',
    country: 'Philippines',
    locationType: 'remote' as const,
    jobType: 'full-time' as const,
    salaryMin: 85000,
    salaryMax: 130000,
    currency: 'PHP',
    experienceRequired: 4,
    skills: ['Docker', 'Kubernetes', 'AWS', 'Terraform', 'CI/CD'],
    category: 'IT & Software Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Content Writer',
    description: 'Create engaging content for our blog, social media, and marketing materials. Research industry trends and produce high-quality articles.',
    tagline: 'Craft compelling stories that engage audiences',
    companyName: 'Content Creators Hub',
    location: 'Davao',
    country: 'Philippines',
    locationType: 'remote' as const,
    jobType: 'part-time' as const,
    salaryMin: 25000,
    salaryMax: 40000,
    currency: 'PHP',
    experienceRequired: 1,
    skills: ['Copywriting', 'SEO', 'Research', 'WordPress', 'Social Media'],
    category: 'Marketing & Communications',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Business Analyst',
    description: 'Bridge the gap between business needs and technical solutions. Gather requirements, create documentation, and support project implementation.',
    tagline: 'Transform business needs into technical solutions',
    companyName: 'Consulting Partners Inc',
    location: 'Makati',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'full-time' as const,
    salaryMin: 55000,
    salaryMax: 80000,
    currency: 'PHP',
    experienceRequired: 3,
    skills: ['Requirements Analysis', 'SQL', 'JIRA', 'Agile', 'Documentation'],
    category: 'Sales & Business Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'HR Recruitment Specialist',
    description: 'Source and recruit top talent for various positions. Manage the full recruitment cycle from job posting to onboarding.',
    tagline: 'Find and hire the best talent',
    companyName: 'Talent Acquisition Group',
    location: 'Manila',
    country: 'Philippines',
    locationType: 'on-site' as const,
    jobType: 'full-time' as const,
    salaryMin: 35000,
    salaryMax: 50000,
    currency: 'PHP',
    experienceRequired: 2,
    skills: ['Recruitment', 'Interviewing', 'LinkedIn', 'HR Software', 'Communication'],
    category: 'Human Resources',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Backend Developer (Node.js)',
    description: 'Design and develop scalable backend services and APIs. Work with databases, microservices, and cloud infrastructure.',
    tagline: 'Build robust backend systems',
    companyName: 'Backend Innovators',
    location: 'Cebu',
    country: 'Philippines',
    locationType: 'remote' as const,
    jobType: 'full-time' as const,
    salaryMin: 65000,
    salaryMax: 100000,
    currency: 'PHP',
    experienceRequired: 3,
    skills: ['Node.js', 'Express', 'MongoDB', 'REST APIs', 'Microservices'],
    category: 'IT & Software Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Product Manager',
    description: 'Lead product strategy and roadmap. Work cross-functionally to deliver features that delight customers and drive business growth.',
    tagline: 'Shape the future of our products',
    companyName: 'Product Leaders Inc',
    location: 'Bonifacio Global City',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'full-time' as const,
    salaryMin: 95000,
    salaryMax: 150000,
    currency: 'PHP',
    experienceRequired: 5,
    skills: ['Product Strategy', 'Agile', 'User Research', 'Analytics', 'Roadmapping'],
    category: 'Sales & Business Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Graphic Designer',
    description: 'Create visual content for digital and print media. Design marketing materials, social media graphics, and brand assets.',
    tagline: 'Bring creative visions to life',
    companyName: 'Visual Arts Studio',
    location: 'Quezon City',
    country: 'Philippines',
    locationType: 'on-site' as const,
    jobType: 'contract' as const,
    salaryMin: 30000,
    salaryMax: 50000,
    currency: 'PHP',
    experienceRequired: 2,
    skills: ['Adobe Photoshop', 'Illustrator', 'InDesign', 'Branding', 'Typography'],
    category: 'Design & Creative',
    postedAt: new Date(),
    expiresAt: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000), // 60 days
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'QA Automation Engineer',
    description: 'Develop and maintain automated test suites. Ensure quality through comprehensive testing strategies and continuous improvement.',
    tagline: 'Ensure quality through automation',
    companyName: 'Quality First Tech',
    location: 'Manila',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'full-time' as const,
    salaryMin: 60000,
    salaryMax: 90000,
    currency: 'PHP',
    experienceRequired: 3,
    skills: ['Selenium', 'Jest', 'Cypress', 'JavaScript', 'Test Automation'],
    category: 'IT & Software Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Sales Executive',
    description: 'Drive revenue growth by identifying and closing new business opportunities. Build relationships with prospects and existing clients.',
    tagline: 'Drive sales and build lasting relationships',
    companyName: 'Sales Pros PH',
    location: 'Makati',
    country: 'Philippines',
    locationType: 'on-site' as const,
    jobType: 'full-time' as const,
    salaryMin: 40000,
    salaryMax: 70000,
    currency: 'PHP',
    experienceRequired: 2,
    skills: ['Sales', 'Negotiation', 'CRM', 'Lead Generation', 'Presentation'],
    category: 'Sales & Business Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Cybersecurity Analyst',
    description: 'Monitor and protect company systems from security threats. Conduct vulnerability assessments and implement security measures.',
    tagline: 'Protect systems from cyber threats',
    companyName: 'SecureNet Solutions',
    location: 'Pasig',
    country: 'Philippines',
    locationType: 'on-site' as const,
    jobType: 'full-time' as const,
    salaryMin: 75000,
    salaryMax: 120000,
    currency: 'PHP',
    experienceRequired: 4,
    skills: ['Network Security', 'Penetration Testing', 'SIEM', 'Firewall', 'Compliance'],
    category: 'IT & Software Development',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Video Editor',
    description: 'Edit video content for social media, marketing campaigns, and corporate communications. Create engaging visual stories.',
    tagline: 'Create captivating video content',
    companyName: 'Media Productions Co',
    location: 'Manila',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'part-time' as const,
    salaryMin: 28000,
    salaryMax: 45000,
    currency: 'PHP',
    experienceRequired: 2,
    skills: ['Adobe Premiere Pro', 'After Effects', 'Color Grading', 'Motion Graphics', 'Storytelling'],
    category: 'Design & Creative',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Financial Analyst',
    description: 'Analyze financial data and create reports to support business decisions. Develop financial models and forecasts.',
    tagline: 'Drive financial insights and planning',
    companyName: 'Finance Partners Ltd',
    location: 'Bonifacio Global City',
    country: 'Philippines',
    locationType: 'on-site' as const,
    jobType: 'full-time' as const,
    salaryMin: 55000,
    salaryMax: 85000,
    currency: 'PHP',
    experienceRequired: 3,
    skills: ['Excel', 'Financial Modeling', 'SQL', 'Tableau', 'Financial Analysis'],
    category: 'Finance & Accounting',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Cloud Architect',
    description: 'Design and implement cloud infrastructure solutions. Lead cloud migration projects and optimize cloud costs.',
    tagline: 'Architect scalable cloud solutions',
    companyName: 'Cloud Experts Inc',
    location: 'Makati',
    country: 'Philippines',
    locationType: 'remote' as const,
    jobType: 'full-time' as const,
    salaryMin: 110000,
    salaryMax: 180000,
    currency: 'PHP',
    experienceRequired: 6,
    skills: ['AWS', 'Azure', 'GCP', 'Cloud Architecture', 'Terraform'],
    category: 'Engineering & Technical',
    postedAt: new Date(),
    isActive: true,
  },
  {
    agencyId: 'sample-agency-001',
    title: 'Project Coordinator',
    description: 'Support project managers in planning and executing projects. Track progress, manage documentation, and coordinate team activities.',
    tagline: 'Keep projects on track and organized',
    companyName: 'Project Solutions Group',
    location: 'Quezon City',
    country: 'Philippines',
    locationType: 'hybrid' as const,
    jobType: 'full-time' as const,
    salaryMin: 38000,
    salaryMax: 55000,
    currency: 'PHP',
    experienceRequired: 1,
    skills: ['Project Management', 'MS Office', 'Communication', 'Organization', 'Time Management'],
    category: 'Administrative & Clerical',
    postedAt: new Date(),
    isActive: true,
  },
];

async function addSampleJobs() {
  console.log('Starting to add sample jobs...');

  const jobsCollection = collection(db, 'jobs');
  let successCount = 0;
  let errorCount = 0;

  for (const job of sampleJobs) {
    try {
      // Convert Date objects to Firestore Timestamps
      const jobData = {
        ...job,
        postedAt: Timestamp.fromDate(job.postedAt),
        ...(job.expiresAt && { expiresAt: Timestamp.fromDate(job.expiresAt) }),
      };

      const docRef = await addDoc(jobsCollection, jobData);
      console.log(`✓ Added job: ${job.title} (ID: ${docRef.id})`);
      successCount++;
    } catch (error) {
      console.error(`✗ Failed to add job: ${job.title}`, error);
      errorCount++;
    }
  }

  console.log('\n=== Summary ===');
  console.log(`Successfully added: ${successCount} jobs`);
  console.log(`Failed: ${errorCount} jobs`);
  console.log('Done!');
}

// Run the function
addSampleJobs().catch(console.error);
